
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMINUSleftPLUSleftTIMESrightUMINUSNUMBER PLUS MINUS TIMESexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : MINUS expression %prec UMINUSexpression : expression TIMES expressionexpression : NUMBER'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,],[1,1,-5,5,-3,1,1,1,-2,-1,-4,]),'PLUS':([2,3,4,8,9,10,],[-5,6,-3,6,-1,-4,]),'NUMBER':([0,1,5,6,7,],[2,2,2,2,2,]),'TIMES':([2,3,4,8,9,10,],[-5,7,-3,7,7,-4,]),'$end':([2,3,4,8,9,10,],[-5,0,-3,-2,-1,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,5,6,7,],[3,4,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','parser.py',14),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','parser.py',18),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',22),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','parser.py',26),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',30),
]
